addons:
  apt:
    update: true
    packages:
      - graphviz
      - ditaa
language: java
script: ./gradlew generateHtml
after_success:
- cd build/html5
- git init
- git config user.name "${GH_USER_NAME}"
- git config user.email "{GH_USER_EMAIL}"
- git add . ; git commit -m "Deploy to GitHub Pages"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages